name: navigation_view
description: NavigationView is a Flutter package that provides a customizable navigation bar with animated transitions.
version: 1.0.7
homepage: https://github.com/PuzzleTakX
repository: https://github.com/PuzzleTakX/navigation_view

environment:
  sdk: '>=2.12.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
